# This is a global allowlist which has a higher order of precedence than rule-specific allowlists.
# If a commit listed in the `commits` field below is encountered then that commit will be skipped and no
# secrets will be detected for said commit. The same logic applies for regexes and paths.
[allowlist]
description = "global allow list"
paths = [
  '''gitleaks\.toml''',
  '''dot_config/nvim/plugged/vimagit/test/renameFile/renameFile_djooks_settings_without_spaces_py_file_diff.expect'''
  '''dot_oh-my-zsh/plugins/macos/spotify'''
]
